import time
import unittest

import jwt

from config import API_KEY, BADGE_TOKEN_TTL_SECONDS, JWT_SECRET
from src.access_system import AccessController


class BadgeTokenExpiryTests(unittest.TestCase):
    """Badge tokens are displayed as an on-screen QR, so they must expire."""

    def setUp(self):
        self.controller = AccessController(port=5011, swipe_timeout=5)
        self.client = self.controller._app.test_client()

    def _token(self, **overrides):
        issued = int(time.time())
        payload = {
            "employee_id": "EMP001",
            "name": "Alice Smith",
            "iat": issued,
            "exp": issued + BADGE_TOKEN_TTL_SECONDS,
        }
        payload.update(overrides)
        return jwt.encode(payload, JWT_SECRET, algorithm="HS256")

    def test_admin_token_carries_expiry(self):
        """The QR generated by /admin must embed an exp claim."""
        response = self.client.get("/admin")
        self.assertEqual(response.status_code, 200)

        html = response.get_data(as_text=True)
        start = html.index("token=") + len("token=")
        token = html[start:].split("&")[0].split('"')[0].split("<")[0].strip()

        claims = jwt.decode(token, JWT_SECRET, algorithms=["HS256"])
        self.assertIn("exp", claims)
        self.assertLessEqual(claims["exp"] - claims["iat"], BADGE_TOKEN_TTL_SECONDS)

    def test_valid_token_is_accepted(self):
        response = self.client.post(
            "/swipe", headers={"Authorization": f"Bearer {self._token()}"}
        )
        self.assertEqual(response.status_code, 200)

    def test_expired_token_is_rejected(self):
        """A token photographed off the screen must stop working once expired."""
        expired = self._token(exp=int(time.time()) - 1)

        response = self.client.post(
            "/swipe", headers={"Authorization": f"Bearer {expired}"}
        )

        self.assertEqual(response.status_code, 401)
        self.assertNotIn("ok", response.get_json().get("status", ""))

    def test_token_signed_with_wrong_secret_is_rejected(self):
        forged = jwt.encode({"employee_id": "EMP666", "name": "Intruder"}, "wrong-secret", algorithm="HS256")

        response = self.client.post(
            "/swipe", headers={"Authorization": f"Bearer {forged}"}
        )

        self.assertEqual(response.status_code, 401)

    def test_swipe_requires_credentials(self):
        self.assertEqual(self.client.post("/swipe", json={"name": "Nobody"}).status_code, 401)


class RateLimitTests(unittest.TestCase):
    """The badge endpoints must throttle brute-force attempts."""

    def test_swipe_is_rate_limited(self):
        controller = AccessController(port=5012, swipe_timeout=5)
        client = controller._app.test_client()

        statuses = [
            client.post(
                "/swipe",
                json={"employee_id": "EMP1", "name": "Alice"},
                headers={"x-api-key": API_KEY},
            ).status_code
            for _ in range(15)
        ]

        self.assertIn(429, statuses, "no request was throttled")


if __name__ == "__main__":
    unittest.main()
